# Generated by Django 5.0.1 on 2024-02-07 15:47

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True



    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
